import '@shared/styles/globals.css';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

//##########################################################################################
// ROOT LAYOUT TYPES
//##########################################################################################
type RootLayoutProps = {
  children: React.ReactNode;
};

//##########################################################################################
// TYPOGRAPHY
//##########################################################################################
const geistSans = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
});

const geistMono = Geist_Mono({
  subsets: ['latin'],
  variable: '--font-geist-mono',
});

//##########################################################################################
// METADATA
//##########################################################################################
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

//##########################################################################################
// ROOT LAYOUT
//##########################################################################################
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
